### ISSUE TITLE
I cant connect to server

### ISSUE THREAD

**Issue by Tealwen** [radistmorse/PEPatch#2]
hi,

with my friends we have opened ports but we don't see any server in the list and i put the ip on filter and click on join but nothing append

**Comment by radistmorse** [comment]
Make sure to apply both client and server patch. Make sure that the server configuration has ```"PublicServer"   : true```. It's false by default. Look at the server logs for the following line

     [Steamworks.NET] GameServer connected successfully

If you still can't see the server in the list after that, please provide the logfiles from both the server and the client.

**Comment by Tealwen** [comment]
`[Log]:8/24/2020 6:57:33 PM
Current server version:273
UnityEngine.Debug:LogFormat(String, Object[])
ServerConfig:InitFromDB() (at C:/Project/0.9Server/Assets/Scripts/Common/ServerConfig.cs:762)
GameServer:Awake() (at C:/Project/0.9Server/Assets/Scripts/GameServer/GameServer.cs:15)

[Log]:8/24/2020 6:57:33 PM
Server initialized on port:9900
UnityEngine.Debug:Log(Object)
uLinkNetwork:uLink_OnServerInitialized() (at C:/Project/0.9Server/Assets/Scripts/Network/uLinkNetwork.cs:73)
UnityEngine.GameObject:SendMessage(String, Object, SendMessageOptions)
#=qzBVPlhHqyune7KfGFdCI6QEUnP0fs1fLWPewHpWItjk=:#=qD5NIjY69Tg$BLsv4qq5MLw==(String, Object)
#=q0zCihwcKnSIMPGpHF0aOTD42bVeGyg6zm2_bNKijhVA=:#=q1ps8gOmgOjy5R1NzpG9zqw==(String, Object)
#=qBsHAklsGYCH8wkaeOQonABxqVuDbW791Ilucxb$6Rgs=:#=qKZaiYVJQietXxTYb6qy5K_toUVerSnDvV8c0YJ$GoQA=(Int32, Int32, Int32)
#=qBsHAklsGYCH8wkaeOQonABxqVuDbW791Ilucxb$6Rgs=:#=q89hRx8A2wwLko1w2EjvTgU7uZC4ga1P1OowMOEsieUo=(Int32, Int32, Boolean)
uLink.Network:InitializeServer(Int32, Int32, Boolean)
NetInterface:InitializeServer(Int32, Int32, Boolean) (at C:/Project/0.9Server/Assets/Scripts/Network/NetInterface.cs:85)
uLinkNetwork:Start() (at C:/Project/0.9Server/Assets/Scripts/Network/uLinkNetwork.cs:47)

[Log]:8/24/2020 6:57:35 PM
ServerInfo--ServerName:LaTeam, MasterRole:Droopi29, MapSeed:patheamaria, GameMode:Story, GameType:Cooperation, Monster:True, Major Bioma:GrassLand, Climate:CT_Temperate, TeamNum:1, NumPerTeam:16, UnlimitedRes:True,TerrainHeight:512, MapSize:0, RiverDensity:1, RiverWidth:1,PlainHeight:20,Flatness:25,BridgeMaxHeight:100,AllyCount:4, Version:V1.1.3
UnityEngine.Debug:Log(Object)
uLinkNetwork:uLink_OnServerInitialized() (at C:/Project/0.9Server/Assets/Scripts/Network/uLinkNetwork.cs:85)
UnityEngine.GameObject:SendMessage(String, Object, SendMessageOptions)
#=qzBVPlhHqyune7KfGFdCI6QEUnP0fs1fLWPewHpWItjk=:#=qD5NIjY69Tg$BLsv4qq5MLw==(String, Object)
#=q0zCihwcKnSIMPGpHF0aOTD42bVeGyg6zm2_bNKijhVA=:#=q1ps8gOmgOjy5R1NzpG9zqw==(String, Object)
#=qBsHAklsGYCH8wkaeOQonABxqVuDbW791Ilucxb$6Rgs=:#=qKZaiYVJQietXxTYb6qy5K_toUVerSnDvV8c0YJ$GoQA=(Int32, Int32, Int32)
#=qBsHAklsGYCH8wkaeOQonABxqVuDbW791Ilucxb$6Rgs=:#=q89hRx8A2wwLko1w2EjvTgU7uZC4ga1P1OowMOEsieUo=(Int32, Int32, Boolean)
uLink.Network:InitializeServer(Int32, Int32, Boolean)
NetInterface:InitializeServer(Int32, Int32, Boolean) (at C:/Project/0.9Server/Assets/Scripts/Network/NetInterface.cs:85)
uLinkNetwork:Start() (at C:/Project/0.9Server/Assets/Scripts/Network/uLinkNetwork.cs:47)

[Log]:8/24/2020 6:57:39 PM
[Steamworks.NET] GameServer connected successfully
UnityEngine.Debug:Log(Object)
PEServerPatch.SteamManager:ServerConnectedCallback(SteamServersConnected_t)
Steamworks.Callback`1:OnRunCallback(IntPtr)
Steamworks.NativeMethods:SteamGameServer_RunCallbacks()
Steamworks.GameServer:RunCallbacks()
PEServerPatch.SteamManager:Update()`

**Comment by radistmorse** [comment]
Which ports did you open? Run ```netstat -p UDP -ao``` from the windows command line on the system where the server is running.

**Comment by Tealwen** [comment]
Proto  Adresse locale         Adresse distante       État
  UDP    0.0.0.0:123            *:*                                    7008
  UDP    0.0.0.0:500            *:*                                    3496
  UDP    0.0.0.0:3702           *:*                                    3000
  UDP    0.0.0.0:3702           *:*                                    3000
  UDP    0.0.0.0:4500           *:*                                    3496
  UDP    0.0.0.0:5050           *:*                                    6960
  UDP    0.0.0.0:5353           *:*                                    11728
  UDP    0.0.0.0:5353           *:*                                    2176
  UDP    0.0.0.0:5353           *:*                                    11728
  UDP    0.0.0.0:5353           *:*                                    11728
  UDP    0.0.0.0:5353           *:*                                    11728
  UDP    0.0.0.0:5355           *:*                                    2176
  UDP    0.0.0.0:9900           *:*                                    5232
  UDP    0.0.0.0:9920           *:*                                    5232
  UDP    0.0.0.0:27036          *:*                                    3696
  UDP    0.0.0.0:49664          *:*                                    3640
  UDP    0.0.0.0:51533          *:*                                    3000
  UDP    0.0.0.0:52812          *:*                                    5232
  UDP    0.0.0.0:53790          *:*                                    3728
  UDP    0.0.0.0:55139          *:*                                    10932
  UDP    0.0.0.0:55441          *:*                                    12652
  UDP    0.0.0.0:56426          *:*                                    5232
  UDP    0.0.0.0:58905          *:*                                    3864
  UDP    0.0.0.0:60057          *:*                                    5232
  UDP    0.0.0.0:60489          *:*                                    3696
  UDP    25.56.160.210:137      *:*                                    4
  UDP    25.56.160.210:138      *:*                                    4
  UDP    25.56.160.210:1900     *:*                                    11964
  UDP    25.56.160.210:2177     *:*                                    11784
  UDP    25.56.160.210:5353     *:*                                    3728
  UDP    25.56.160.210:5353     *:*                                    3640
  UDP    25.56.160.210:50562    *:*                                    11964
  UDP    127.0.0.1:1900         *:*                                    11964
  UDP    127.0.0.1:10020        *:*                                    10536
  UDP    127.0.0.1:10021        *:*                                    1080
  UDP    127.0.0.1:49666        *:*                                    2932
  UDP    127.0.0.1:50564        *:*                                    11964
  UDP    127.0.0.1:65240        *:*                                    1552
  UDP    127.0.0.1:65425        *:*                                    3652
  UDP    127.0.0.1:65426        *:*                                    3652
  UDP    192.168.1.70:137       *:*                                    4
  UDP    192.168.1.70:138       *:*                                    4
  UDP    192.168.1.70:1900      *:*                                    11964
  UDP    192.168.1.70:2177      *:*                                    11784
  UDP    192.168.1.70:5353      *:*                                    3640
  UDP    192.168.1.70:5353      *:*                                    3728
  UDP    192.168.1.70:50563     *:*                                    11964
  UDP    192.168.1.70:55440     *:*                                    12652

**Comment by radistmorse** [comment]
Yep, looks correct. You need to open ports 9900 and 9920, and the server should appear in the list.

**Comment by Tealwen** [comment]
work thanks , for your work
